### ISSUE TITLE
Upgrade to latest open release

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/start-specific-workflow#1]
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by EliJDonahue** [comment]
Retarget to current open release: 11.0 SP12.

**Comment by PremalBhagat** [comment]
Updated and tested to current open release: 11.0 SP12 and created pull request for the same

**Comment by sampoearas** [comment]
Verified on 11.0 SP12, SP15
